import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";
import { work_sans } from "./assets/fonts/fonts";


export const metadata: Metadata = {
   title: "Home",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={work_sans.className}>
            <Header />
            {children}
         </body>
      </html>
   );
}
